### ISSUE TITLE
水曜日グループ

### ISSUE THREAD

**Issue by manasan-iTL** [winc1980/www.winc.ne.jp#115]
それぞれのタスクとissues　例

安心と信頼のあるサイト　デザインが統一されていると良いのでは？
・Formを自分で書いてみて、サイトとのデザインと統一性を持たせる。
・入会者用とHP用とのデザインを統一
・ページ内リンクになっているのが分かりづらい。
・入会者用とHPの背景の統一
などなど、あくまで一例。

上のIssueは粒度が大きい。　デザインを統一とは全部？それとも一部？

できるだけ、小さいところから直していこう！

**Comment by susaki2002** [comment]
「よくあるご質問」→「お問い合わせ」にタイトルを変更する

**Comment by susaki2002** [comment]
活動日程の欄に、各チームの活動日のリストまたは表を追加する

**Comment by aka-luce** [comment]
チャットボットの情報が古いので新しくする

**Comment by susaki2002** [comment]
お問い合わせ>Twitterから の項目を
「Twitter で @winc_w にダイレクトメッセージを送ってください。」
　↓
「Twitter で @winc_w にダイレクトメッセージを送ってください。質問箱から匿名で質問を送ることもできます。」
などと変更（質問箱について記載する）
