### ISSUE TITLE
未経験者の割合の追加

### ISSUE THREAD

**Issue by ShotaOgino** [winc1980/www.winc.ne.jp#119]

**Comment by kanako0424** [comment]
assigneesからassin yourselfで自分を割り当ててください。

対応するプルリクに、 
"close #119 " という一行を追加してください。

**Comment by ShotaOgino** [comment]
変更しました。
夜中にお疲れ様です。

ギリギリ間に合いませんでした、、

2022年8月1日(月) 0:36 kanakoHamada ***@***.***>:
