### ISSUE TITLE
活動部門に部門を追加する

### ISSUE THREAD

**Issue by Mow17** [winc1980/www.winc.ne.jp#52]
- HPチーム、セキュリティチーム、競プロチーム、Pythonチーム、プロジェクションマッピングチーム
- 上の五つを今年度の活動チームとする。
- Pythonチームは新しく作成し、スクレイピングをする

**Comment by kanako0424** [comment]
これ絶対変わっている。PMはないし、Pythonのスクレイピングは多分やらないよね。
