### ISSUE TITLE
landbot.ioに部門情報を対応させる

### ISSUE THREAD

**Issue by Mow17** [winc1980/www.winc.ne.jp#56]
- landbot.ioにハロプロ部門などが書いてあるので、削除する。
- HPチームなどの情報を追加する。

**Comment by kanako0424** [comment]
landbotはlandbotのサイトで更新しないといけないです。もし部門がまた増えて、情報を更新するのが大変だったら、一旦 landbotのボタンを削除しておく手もあるけど、今の所の情報に直すか、ボタンを削除するか、どちかどちらがいい？

**Comment by kanako0424** [comment]
landbotのボタンは削除しました。
